
version: "3.4"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - dev-network
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: danielzz91/chat-app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - dev-network
  redis:
    container_name: redis-container
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - dev-network

networks:
  dev-network:

