version: "3.4"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
  redis:
    container_name: redis-container
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data